### PR TITLE
Add migration 001: create figures table

### PR DESCRIPTION
**Pull request by brebory**
Adds the first Sequel migration for the figures table.

### CODE REVIEW

**Comment by Beznus** [comment]
So this looks good, but I have no idea what pokemans do

**Comment by Beznus** [comment]
how do I approve this?

**Comment by Beznus** [comment]
@brebory

**Comment by brebory** [comment]
@Beznus 

Go to the "Files Changed" tab, then there should be a green review button in the upper right. Click that and a dropdown with review options appears.

**Pull request merged**
